### ISSUE TITLE
KeyError: 'DG-Lab Coyote'

### ISSUE THREAD

**Issue by Iluvatar33** [MinLL/GameInterfaceForToys#25]
I the settings in GIFT 1.4.4 wont save. It keeps having KeyError: 'DG-Lab Coyote' every time i try to save settings.
![Screenshot 2024-08-16](https://github.com/user-attachments/assets/86d0da02-5530-4f85-8da8-9933f7b2fd48)

**Comment by sorasky12** [comment]
I'm experiencing the exact same issue

**Comment by inertaert** [comment]
Hello!

I am an occasional contributor to this project. @MinLL hasn't been heard from for quite a while, so in the meantime I'm maintaining a separate fork of the codebase where this issue has already been fixed.

You can [download the latest version here](https://github.com/inertaert/GameInterfaceForToys/releases).

Let me know if it works for you.

Cheers.

**Comment by ArdisFoxx** [comment]
@inertaert the exe on your fork is detected as having malware.

**Comment by inertaert** [comment]
> @inertaert the exe on your fork is detected as having malware.

Yup, I get warnings from Windows Defender too, though I don't know why. 

I'm positive it's a false positive (heh), either because the code includes functionality to hook into the memory of processes (that's for Elden Ring support), or because the code is being wrapped up in one big executable with Pyinstaller, which seems fishy for antivirus software.

Luckily, the code is open source and the build process is automated via GitHub Actions. It's all out in the open. You can see the build workflow for the latest release here: https://github.com/inertaert/GameInterfaceForToys/actions/workflows/build-release.yml .

If anybody knows how to fix this, feel free to get in touch.

Best regards.

**Comment by inertaert** [comment]
With [release 1.4.5](https://github.com/MinLL/GameInterfaceForToys/releases), this issues has been resolved. Paging @MinLL to close the issue.

Thanks.

**Comment by MinLL** [comment]
Fixed in 1.4.5. Thanks @inertaert
